language: scala
scala: 2.11.12
jdk: oraclejdk8

script:
  - sbt +test
  - ./change-scala-versions.sh "2.11"
  - mvn -q clean package
  - ./change-scala-versions.sh "2.10"
  - mvn -q clean package

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.m2

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - find $HOME/.m2         -name "*.lastUpdated"        -print -delete

after_success:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - find $HOME/.m2         -name "*.lastUpdated"        -print -delete
