language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7

# for running tests on Travis CI container infrastructure for faster builds
sudo: true

before_install:
  - sudo apt-get install build-essential   blas  git
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
script:
  -  cd /home/travis/build/deeplearning4j/nd4j && chmod +x ./runtests.sh && ./runtests.sh