language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk7

# for running tests on Travis CI container infrastructure for faster builds
sudo: true

env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=1.9.2



before_install:
  - sudo yum -y install blas

script:
  - mvn clean install -DskipTests
  - cd nd4j-x86 && mvn clean test